'use strict';

angular.module('pilvivaylaTerminatorsApp')
  .controller('SubjectCtrl', function ($scope) {
    $scope.postsCount = 15;
	$scope.title = $scope.subject;
	$scope.items = [
    {'name': 'Music Theory and Practice',
     'author': 'Someone',
     'image': '/images/apps/1.jpg', 
     'price': '2,99€',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Better Ears for iPad',
     'author': 'Someone',
     'image': '/images/apps/2.png', 
     'price': 'free',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Grade 1 Music Theory',
     'author': 'Someone',
     'image': '/images/apps/3.jpg', 
     'price': '2,99€',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Music Theory Pro',
     'author': 'Someone',
     'image': '/images/apps/4.jpg', 
     'price': '2,99€',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Music Tool LE',
     'author': 'Someone',
     'image': '/images/apps/5.png', 
     'price': '2,99€',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Nota for iPad',
     'author': 'Someone',
     'image': '/images/apps/6.jpg', 
     'price': '2,99€',
     'type': 'Application',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Scales and Modes for iPad',
     'author': 'Someone',
     'image': '/images/apps/7.png', 
     'price': '2,99€',
     'type': 'Application',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Theory Lessons',
     'author': 'Someone',
     'image': '/images/apps/8.png', 
     'price': '2,99€',
     'type': 'Application',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	 {'name': 'Nexus S',
     'author': 'Someone',
     'image': '/images/apps/1.jpg', 
     'price': '2,99€',
     'type': '',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	  	 {'name': 'Nexus S',
     'author': 'Someone',
     'image': '/images/apps/1.jpg', 
     'price': '2,99€',
     'type': '',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	  	 {'name': 'Nexus S',
     'author': 'Someone',
     'image': '/images/apps/1.jpg', 
     'price': '2,99€',
     'type': '',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''},
 	  	 {'name': 'Nexus S',
     'author': 'Someone',
     'image': '/images/apps/1.jpg', 
     'price': '2,99€',
     'type': '',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'askjfd öasdjk fldkasfj adjskf asdfsa fkasdlf asdf',
 	 'description_long': ''}
  ];
  });
