'use strict';

angular.module('pilvivaylaTerminatorsApp')
  .controller('SubjectCtrl', function ($scope) {
    $scope.postsCount = 15;
	$scope.title = $scope.subject;
	$scope.items = [
    {'name': 'Music Theory and Practice',
     'author': 'Musicopoulos',
     'image': '/images/apps/1.jpg', 
     'price': '2,99',
     'type': 'Program',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Combining structured music theory lessons with matching exercises ..',
 	 'description_long': ''},
 	 {'name': 'Better Ears for iPad',
     'author': 'appsolute GmbH',
     'image': '/images/apps/2.png', 
     'price': '14.99',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Better Ears helps you grow your musical skills and enhance your hearing capabilities.',
 	 'description_long': ''},
 	 {'name': 'Grade 1 Music Theory',
     'author': 'Zuztertu Ltd',
     'image': '/images/apps/3.jpg', 
     'price': '2,49',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'In addition to explanatory text, it also contains audio, illustrations...',
 	 'description_long': ''},
 	 {'name': 'Music Theory Pro',
     'author': 'Joel Clifft',
     'image': '/images/apps/4.jpg', 
     'price': '4,99',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'A little friendly competition turns boring drills into an exciting game.',
 	 'description_long': ''},
 	 {'name': 'Music Tool LE',
     'author': 'TheWay',
     'image': '/images/apps/5.png', 
     'price': 'Free',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '3',
     'description_short': 'Explore the world of music with Music Tool - a huge variety of scales from around the globe at your fingertips.',
 	 'description_long': ''},
 	 {'name': 'Nota for iPad',
     'author': 'Melvin River',
     'image': '/images/apps/6.jpg', 
     'price': '2,99',
     'type': 'Application',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Nota has a piano chord and scale browser, a piano and staff note locator,...',
 	 'description_long': ''},
 	 {'name': 'Scales and Modes for iPad',
     'author': 'Smappsoft',
     'image': '/images/apps/7.png', 
     'price': '1,99',
     'type': 'Application',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Scales & Modes is an interactive visual and audio reference for the diatonic scales and modes... ',
 	 'description_long': ''},
 	 {'name': 'Theory Lessons',
     'author': 'musictheory.net',
     'image': '/images/apps/8.png', 
     'price': '2,99',
     'type': 'Application',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Theory Lessons features 39 music theory lessons from musictheory.net, presented in their original animated versions',
 	 'description_long': ''},
 	  {'name': 'Music Theory and Practice',
     'author': 'Musicopoulos',
     'image': '/images/apps/1.jpg', 
     'price': '2,99',
     'type': 'Program',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Combining structured music theory lessons with matching exercises ..',
 	 'description_long': ''},
 	 {'name': 'Better Ears for iPad',
     'author': 'appsolute GmbH',
     'image': '/images/apps/2.png', 
     'price': '14.99',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'Better Ears helps you grow your musical skills and enhance your hearing capabilities.',
 	 'description_long': ''},
 	 {'name': 'Grade 1 Music Theory',
     'author': 'Zuztertu Ltd',
     'image': '/images/apps/3.jpg', 
     'price': '2,49',
     'type': 'Game',
     'platform': 'iOS',
     'licence': '', 
     'rating': '4',
     'description_short': 'In addition to explanatory text, it also contains audio, illustrations...',
 	 'description_long': ''},
  ];
  });
